{% set name = "pygmsh" %}
{% set version = "7.1.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygmsh-{{ version }}.tar.gz
  sha256: 563724abff4f8517598d3354b9c795feddbe0675786145bfeaf20cbee6691c1d

build:
  entry_points:
    - pygmsh-optimize = pygmsh._cli:optimize_cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
    - libgl-devel  # [linux]
    # The dependencies are required for installation 
    - python-gmsh
    - meshio >=4.3.2,<6
    - numpy >=1.20.0
  run:
    - python
    - python-gmsh
    - meshio >=4.3.2,<6
    - numpy >=1.20.0

test:
  imports:
    - pygmsh
  commands:
    - pygmsh-optimize --help

about:
  summary: Python frontend for Gmsh
  home: https://github.com/nschloe/pygmsh
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
