schema_version: 1

context:
  name: pygmsh
  version: "7.1.17"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pygmsh-${{ version }}.tar.gz
  sha256: 563724abff4f8517598d3354b9c795feddbe0675786145bfeaf20cbee6691c1d

build:
  number: 3
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pygmsh-optimize = pygmsh._cli:optimize_cli

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
    - if: linux
      then: libgl-devel
    # The dependencies are required for installation
    - python-gmsh
    - meshio >=4.3.2,<6
    - numpy >=1.20.0
  run:
    - python
    - python-gmsh
    - meshio >=4.3.2,<6
    - numpy >=1.20.0

tests:
  - python:
      imports:
        - pygmsh
      pip_check: false
  - script:
      - pygmsh-optimize --help

about:
  summary: Python frontend for Gmsh
  license: GPL-3.0-only
  license_file: LICENSE.txt
  homepage: https://github.com/nschloe/pygmsh

extra:
  recipe-maintainers:
    - jan-janssen
